// Generated by CoffeeScript 1.7.1
(function() {
  window.jTester.AES = {
    encrypt: function(key, data) {
      var encrypted;
      key = CryptoJS.enc.Utf8.parse(key);
      data = CryptoJS.enc.Utf8.parse(data);
      encrypted = CryptoJS.AES.encrypt(data, key, {
        mode: CryptoJS.mode.ECB
      });
      return encrypted.ciphertext.toString(CryptoJS.enc.Base64);
    },
    decrypt: function(key, data) {
      var decrypted;
      key = CryptoJS.enc.Utf8.parse(key);
      decrypted = CryptoJS.AES.decrypt(data, key, {
        mode: CryptoJS.mode.ECB
      });
      return decrypted.toString(CryptoJS.enc.Utf8);
    }
  };

  window.jTester.utils = {
    getRandomString: function(l) {
      var temp, x;
      x = "0123456789abcefghijklmnopqrstuvwxyzABCEFGHIJKLMNOPQRSTUVWXYZ";
      temp = '';
      while (l >= 0) {
        temp += x.charAt(Math.ceil(Math.random() * 100000000) % x.length);
        l--;
      }
      return temp;
    },
    getMd5Hash: function(str) {
      return CryptoJS.MD5(str + '').toString(CryptoJS.enc.Hex);
    },
    getGuid: function() {
      return UUID.v4().replace(/-/g, "");
    }
  };

}).call(this);
