// Generated by CoffeeScript 1.8.0
(function() {
  var require;

  window.jTester = {};

  require = window.require;

  window.jTester.require = {
    nw: require('nw.gui'),
    fs: require('fs'),
    path: require('path'),
    querystring: require('querystring'),
    url: require('url'),
    request: require('./node_modules/request'),
    uuid: require('./node_modules/node-uuid'),
    formdata: require('./node_modules/request/node_modules/form-data')
  };

  process.on('uncaughtException', function(err) {
    return alert(err.message);
  });

  window.angularapp = angular.module('jTester', ['ui.bootstrap', 'angularFileUpload']);

  require('./node_modules/coffee-script/register');

  require('./coffee/config.coffee');

  require('./coffee/utils/utils.coffee');

  require('./coffee/views/indexctrl.coffee');

  require('./coffee/views/configctrl.coffee');

  require('./coffee/views/globalitemctrl.coffee');

  require('./coffee/views/downlistctrl.coffee');

  require('./coffee/views/uploadfilectrl.coffee');

  require('./coffee/views/savefilectrl.coffee');

  require('./coffee/utils/httputils.coffee');

  jTester.restart = function() {
    var child, child_process;
    jTester.require.nw.Window.get().hide();
    child_process = require("child_process");
    child = child_process.spawn(process.execPath, [], {
      detached: true
    });
    child.unref();
    return jTester.require.nw.App.quit();
  };

}).call(this);
